#  ___
# | _ \_  _ _ _ ___ ___    ____ _               _
# |  _/ || | '_(_-</ -_)  / ___| |__   ___  ___| | _____ _ __
# |_|  \_,_|_| /__/\___| | |   | '_ \ / _ \/ __| |/ / _ \ '__|
#                        | |___| | | |  __/ (__|   <  __/ |
#    DevDauXanh#6857      \____|_| |_|\___|\___|_|\_\___|_|

#You need to put your license info here to active this shjt keker
license:
  key: xxxxx
  user: xxxxx

#Custom setting for checker
settings:
  proxy-loader:
    #type of proxy (HTTP/SOCKS4/SOCKS5)
    type: HTTP
    # true => when run, this keker will open form to choose proxy file
    # false => keker will use default proxy file!
    custom-choose: true

  combo-loader:
    # true => when run, this keker will open form to choose combo file
    # false => keker will use default combo file!
    custom-choose: true

  #number of thread will run to check combo, required greater than 0
  threads: 200

  #setting connect to account
  connection:
    #number of times retries to check account
    retries: 2
    #time to wait to check other account or retry (milliseconds)
    wait: 1000
    #time to read info of account then disconnect (seconds)
    time-out: 10

  #setting for account had checked
  checked-config:
    capture:
      #print account if hit
      hit: true
      #print account if failed
      fail: true

    #export to file
    save:
      #export hit accounts
      hit: false
      #export failed accounts
      fail: true
